"""
Play out and align a reset/inhibitor Petri net.

This example uses the hospital-discharge model stored in the test data. It
demonstrates the two places where custom Petri-net semantics must be supplied:

1. basic playout, so inhibitor arcs affect enablement and reset arcs affect
   firing;
2. the semantics-aware Dijkstra alignment variant, so its state-space search
   follows exactly the same rules as the model simulation.

Run this file from any working directory:

    python examples/inhibitor_reset_playout_and_alignment.py
"""

import sys
from pathlib import Path

# A directly executed file puts examples/ (not the repository root) first on
# sys.path. Add the checkout root before importing PM4Py so this example uses
# the local implementation, including VERSION_DIJKSTRA_SEMANTICS.
REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPOSITORY_ROOT))

import pm4py
from pm4py.algo.conformance.alignments.petri_net import (
    algorithm as alignments,
)
from pm4py.algo.simulation.playout.petri_net import algorithm as playout
from pm4py.objects.log.obj import Event, EventLog, Trace
from pm4py.objects.petri_net.inhibitor_reset.semantics import (
    InhibitorResetSemantics,
)
from pm4py.objects.petri_net.obj import InhibitorNet, ResetNet


# Resolve input files relative to this source file. Using __file__ instead of
# the current working directory makes the example work both from the repository
# root and from the examples directory.
DATA_DIR = REPOSITORY_ROOT / "tests" / "input_data" / "inh_res_nets"
MODEL_PATH = DATA_DIR / "hospital_discharge.pnml"
LOG_PATH = DATA_DIR / "logs" / "hospital_discharge.xes"


def activity_sequence(trace: Trace):
    """Return only the readable activity names from a PM4Py trace."""
    return [event["concept:name"] for event in trace]


def execute_script():
    # PNML preserves the specialized reset and inhibitor arc types. The PM4Py
    # importer therefore reconstructs a ResetInhibitorNet automatically.
    net, initial_marking, final_marking = pm4py.read_pnml(str(MODEL_PATH))

    # The companion XES file was generated by basic playout. Requesting the
    # legacy EventLog representation gives us Trace/Event objects, which can be
    # passed directly to the alignment API used below.
    stored_log = pm4py.read_xes(
        str(LOG_PATH), return_legacy_log_object=True
    )

    # A reset arc consumes every token from its source place when its transition
    # fires. An inhibitor arc does not consume tokens; instead, it enables its
    # transition only while the source place is empty. Checking the imported
    # objects is a useful sanity check that PNML round-tripping retained both.
    reset_arcs = [
        arc for arc in net.arcs if isinstance(arc, ResetNet.ResetArc)
    ]
    inhibitor_arcs = [
        arc for arc in net.arcs if isinstance(arc, InhibitorNet.InhibitorArc)
    ]
    assert reset_arcs, "the imported model should contain a reset arc"
    assert inhibitor_arcs, "the imported model should contain an inhibitor arc"

    print("Model:", net.name)
    print("Visible activities:", len([t for t in net.transitions if t.label]))
    print("Stored traces:", len(stored_log))
    print("First stored trace:", activity_sequence(stored_log[0]))

    # ClassicSemantics remains PM4Py's default because it is right for ordinary
    # Petri nets. This model is not ordinary, so the same specialized semantics
    # object is deliberately passed to both playout and alignment.
    semantics = InhibitorResetSemantics()

    # Generate a few fresh traces. "add_only_if_fm_is_reached" excludes partial
    # runs stopped by the length limit, while maxTraceLength protects us from an
    # unlucky sequence that repeatedly chooses one of the model's optional
    # loops.
    simulated_log = playout.apply(
        net,
        initial_marking,
        final_marking,
        variant=playout.Variants.BASIC_PLAYOUT,
        parameters={
            "petri_semantics": semantics,
            "noTraces": 5,
            "maxTraceLength": 40,
            "add_only_if_fm_is_reached": True,
        },
    )

    print("\nFreshly simulated traces:")
    for index, trace in enumerate(simulated_log):
        print(f"  {index}: {activity_sequence(trace)}")

    # VERSION_DIJKSTRA_SEMANTICS searches states of the form
    # (position in trace, model marking). For each model or synchronous move it
    # calls the supplied semantics to find enabled transitions and fire them.
    # This avoids flattening the model into a classic synchronous-product net,
    # which would lose the special behavior of reset and inhibitor arcs.
    alignment_results = alignments.apply(
        simulated_log,
        net,
        initial_marking,
        final_marking,
        variant=alignments.Variants.VERSION_DIJKSTRA_SEMANTICS,
        parameters={
            "petri_semantics": semantics,
            "show_progress_bar": False,
        },
    )

    # Every trace came from this exact model, so every event should synchronize
    # with a model transition and every optimal alignment should cost zero.
    assert all(result["cost"] == 0 for result in alignment_results)
    print("\nAlignment costs for simulated traces:")
    print([result["cost"] for result in alignment_results])

    # Finally, insert an event that the model does not know. Dijkstra represents
    # it as a log move: ("Unexpected Manual Override", ">>"). With PM4Py's
    # standard costs that deviation contributes 10,000 to the alignment.
    original = simulated_log[0]
    deviating_trace = Trace(
        [Event(dict(event)) for event in original],
        attributes=dict(original.attributes),
    )
    deviating_trace.insert(
        1, Event({"concept:name": "Unexpected Manual Override"})
    )
    deviation = alignments.apply(
        deviating_trace,
        net,
        initial_marking,
        final_marking,
        variant=alignments.Variants.VERSION_DIJKSTRA_SEMANTICS,
        parameters={"petri_semantics": semantics},
    )

    assert deviation["cost"] == 10000
    assert ("Unexpected Manual Override", ">>") in deviation["alignment"]
    print("\nAlignment of a deliberately deviating trace:")
    print("  cost:", deviation["cost"])
    print("  moves:", deviation["alignment"])

    # EventLog is imported above to make clear that both persisted and simulated
    # logs use PM4Py's normal log type; this assertion also documents the return
    # type of basic Petri-net playout.
    assert isinstance(simulated_log, EventLog)


if __name__ == "__main__":
    execute_script()
